management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: ${ACTUATOR_BASE_PATH}
      exposure:
        include: "health, prometheus"
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  server:
    port: ${ACTUATOR_SERVER_PORT}
spring:
  config:
    activate:
      on-profile: local
